/**
 * كتالوج الأنشطة الرئيسية — منصة رونق متعددة الأنشطة
 */
window.MkenActivitiesCatalog = [
  {
    id: 'maintenance',
    icon: '🔧',
    title: 'التشغيل والصيانة',
    shortTitle: 'صيانة',
    tagline: 'صيانة منزلية متنقلة',
    description: 'خدمات صيانة منزلية متنقلة — فنيون معتمدون يصلون إلى موقعك في جدة.',
    uiProfile: 'field-service',
    defaultTheme: 'terracotta',
    serviceIds: [
      'ac', 'plumbing', 'electrical', 'general',
      'pest-control', 'tank-cleaning', 'insulation', 'appliances',
    ],
    booking: {
      type: 'field-visit',
      requiresAddress: true,
      slotDuration: 120,
      ctaLabel: 'احجز موعد صيانة',
    },
  },
  {
    id: 'tech-digital',
    icon: '💻',
    title: 'الحاسب والتقنية الرقمية',
    shortTitle: 'تقنية',
    tagline: 'حلول رقمية متكاملة',
    description: 'تصميم مواقع، تطبيقات، تحسين محركات البحث، وأنظمة واتساب CRM — حضور رقمي احترافي لعملك.',
    uiProfile: 'project-based',
    defaultTheme: 'slate',
    serviceIds: [
      'web-design', 'mobile-apps', 'landing-pages', 'seo',
      'whatsapp-crm', 'social-media', 'branding', 'ecommerce',
    ],
    booking: {
      type: 'consultation',
      requiresAddress: false,
      slotDuration: 60,
      ctaLabel: 'اطلب استشارة مجانية',
    },
  },
  {
    id: 'it-support',
    icon: '🖥️',
    title: 'صيانة الحاسب والشبكات',
    shortTitle: 'حاسب وIT',
    tagline: 'دعم تقني متنقل',
    description: 'صيانة وتجميع أجهزة الكمبيوتر واللابتوب، إعداد الشبكات، واستعادة البيانات — فنيون IT يصلون إلى موقعك.',
    uiProfile: 'field-service',
    defaultTheme: 'slate',
    serviceIds: [
      'computer', 'laptop-repair', 'network-setup',
      'printer-repair', 'data-recovery', 'virus-removal',
    ],
    booking: {
      type: 'field-visit',
      requiresAddress: true,
      slotDuration: 90,
      ctaLabel: 'احجز فني IT',
    },
  },
  {
    id: 'cleaning',
    icon: '🧹',
    title: 'النظافة والتعقيم',
    shortTitle: 'نظافة',
    tagline: 'نظافة احترافية وتعقيم',
    description: 'تنظيف عميق للمنازل والفلل والمكاتب — تعقيم، تنظيف ما بعد التشطيب، وسجاد وموكيت.',
    uiProfile: 'field-service',
    defaultTheme: 'forest',
    serviceIds: [
      'cleaning', 'office-cleaning', 'post-construction-clean',
      'carpet-cleaning', 'disinfection',
    ],
    booking: {
      type: 'field-visit',
      requiresAddress: true,
      slotDuration: 180,
      ctaLabel: 'احجز موعد نظافة',
    },
  },
  {
    id: 'renovation',
    icon: '🎨',
    title: 'التشطيب والديكور',
    shortTitle: 'تشطيب',
    tagline: 'دهانات ونجارة وتشطيب',
    description: 'دهانات داخلية وخارجية، نجارة وأبواب، بلاط وديكور — فريق تشطيب محترف لمنزلك أو مكتبك.',
    uiProfile: 'field-service',
    defaultTheme: 'desert',
    serviceIds: [
      'painting', 'carpentry', 'tiling', 'wallpaper', 'kitchen-cabinets',
    ],
    booking: {
      type: 'field-visit',
      requiresAddress: true,
      slotDuration: 240,
      ctaLabel: 'اطلب معاينة مجانية',
    },
  },
  {
    id: 'security',
    icon: '🛡️',
    title: 'الأمن والمراقبة',
    shortTitle: 'أمن',
    tagline: 'حماية ومراقبة ذكية',
    description: 'تركيب كاميرات CCTV، أنظمة إنذار، تحكم بالدخول، ومنزل ذكي — حماية متكاملة لمنزلك أو عملك.',
    uiProfile: 'field-service',
    defaultTheme: 'midnight',
    serviceIds: [
      'cameras', 'alarm-systems', 'access-control',
      'intercom', 'smart-home', 'fire-alarm',
    ],
    booking: {
      type: 'field-visit',
      requiresAddress: true,
      slotDuration: 120,
      ctaLabel: 'احجز معاينة أمنية',
    },
  },
  {
    id: 'training',
    icon: '🎓',
    title: 'التدريب والتأهيل',
    shortTitle: 'تدريب',
    tagline: 'ورش ودورات عملية',
    description: 'دورات تقنية ومهنية — أساسيات الحاسب، برامج المكتب، الأمن السيبراني، وإدارة واتساب Business.',
    uiProfile: 'project-based',
    defaultTheme: 'ocean',
    serviceIds: [
      'computer-basics', 'office-apps', 'cyber-awareness',
      'web-basics', 'whatsapp-business-training',
    ],
    booking: {
      type: 'consultation',
      requiresAddress: false,
      slotDuration: 60,
      ctaLabel: 'سجّل في دورة',
    },
  },
  {
    id: 'barber-salon',
    icon: '💈',
    title: 'صالونات الحلاقة والتجميل',
    shortTitle: 'صالون',
    tagline: 'حلاقة وتجميل احترافي',
    description: 'حلاقة رجالية ونسائية، عناية باللحية، صبغ، وخدمات تجميل — احجز موعدك وادخل بدون انتظار.',
    uiProfile: 'appointment-based',
    defaultTheme: 'midnight',
    serviceIds: [
      'mens-haircut', 'beard-grooming', 'kids-haircut', 'hair-dye',
      'facial-mens', 'womens-haircut', 'manicure', 'home-barber',
    ],
    booking: {
      type: 'appointment',
      requiresAddress: false,
      slotDuration: 30,
      ctaLabel: 'احجز موعد صالون',
    },
  },
  {
    id: 'car-care',
    icon: '🚗',
    title: 'مغاسل وعناية السيارات',
    shortTitle: 'سيارات',
    tagline: 'غسيل وتلميع احترافي',
    description: 'غسيل خارجي وداخلي، تلميع، وتنظيف محرك — في المغسلة أو عند موقعك.',
    uiProfile: 'appointment-based',
    defaultTheme: 'ocean',
    serviceIds: [
      'quick-wash', 'full-wash', 'interior-detailing',
      'polish-wax', 'engine-clean', 'mobile-car-wash',
    ],
    booking: {
      type: 'appointment',
      requiresAddress: false,
      slotDuration: 45,
      ctaLabel: 'احجز غسيل سيارة',
    },
  },
  {
    id: 'healthcare',
    icon: '🏥',
    title: 'الخدمات الطبية والصحية',
    shortTitle: 'صحي',
    tagline: 'رعاية صحية موثوقة',
    description: 'كشف طبي، تمريض منزلي، تحاليل، علاج طبيعي، واستشارات عن بُعد — احجز موعدك بسهولة.',
    uiProfile: 'appointment-based',
    defaultTheme: 'forest',
    serviceIds: [
      'gp-consultation', 'home-nursing', 'home-lab',
      'physiotherapy', 'dental-checkup', 'telemedicine',
    ],
    booking: {
      type: 'appointment',
      requiresAddress: false,
      slotDuration: 30,
      ctaLabel: 'احجز موعد طبي',
    },
  },
  {
    id: 'spa-wellness',
    icon: '🧖',
    title: 'سبا ومساج',
    shortTitle: 'سبا',
    tagline: 'استرخاء وعناية',
    description: 'مساج سويدي، حمام مغربي، عناية بالبشرة، وسبا منزلي — احجز جلسة استرخاء.',
    uiProfile: 'appointment-based',
    defaultTheme: 'forest',
    serviceIds: ['swedish-massage', 'moroccan-bath', 'facial-spa', 'body-scrub', 'couples-spa', 'home-spa'],
    booking: { type: 'appointment', requiresAddress: false, slotDuration: 60, ctaLabel: 'احجز جلسة سبا' },
  },
  {
    id: 'fitness',
    icon: '🏋️',
    title: 'رياضة ولياقة',
    shortTitle: 'لياقة',
    tagline: 'تدريب ونشاط',
    description: 'تدريب شخصي، يoga، حصص جماعية، واستشارة تغذية — احجز حصتك.',
    uiProfile: 'appointment-based',
    defaultTheme: 'ocean',
    serviceIds: ['personal-training', 'yoga-session', 'gym-day-pass', 'group-class', 'nutrition-consult'],
    booking: { type: 'appointment', requiresAddress: false, slotDuration: 60, ctaLabel: 'احجز حصة' },
  },
  {
    id: 'veterinary',
    icon: '🐾',
    title: 'خدمات بيطرية',
    shortTitle: 'بيطري',
    tagline: 'رعاية حيوانات أليفة',
    description: 'كشف بيطري، تطعيم، تجميل حيوانات، وزيارة منزلية — احجز موعداً لأليفك.',
    uiProfile: 'appointment-based',
    defaultTheme: 'forest',
    serviceIds: ['vet-checkup', 'pet-vaccination', 'pet-grooming', 'home-vet-visit', 'pet-surgery-consult'],
    booking: { type: 'appointment', requiresAddress: false, slotDuration: 30, ctaLabel: 'احجز موعد بيطري' },
  },
  {
    id: 'restaurant',
    icon: '🍽️',
    title: 'مطاعم وحجز طاولات',
    shortTitle: 'مطاعم',
    tagline: 'احجز طاولتك',
    description: 'حجز طاولة، غرف خاصة، وتذوق — تجربة طعام بدون انتظار.',
    uiProfile: 'appointment-based',
    defaultTheme: 'desert',
    serviceIds: ['table-booking', 'private-dining', 'buffet-reservation', 'catering-tasting'],
    booking: {
      type: 'appointment', requiresAddress: false, slotDuration: 90,
      ctaLabel: 'احجز طاولة', collectPartySize: true,
    },
  },
  {
    id: 'consulting',
    icon: '⚖️',
    title: 'استشارات مهنية',
    shortTitle: 'استشارات',
    tagline: 'خبراء في خدمتك',
    description: 'استشارات قانونية، محاسبة، عقارات، وأعمال — احجز جلسة مع مختص.',
    uiProfile: 'appointment-based',
    defaultTheme: 'midnight',
    serviceIds: ['legal-consult', 'accounting-consult', 'real-estate-viewing', 'business-consult', 'hr-consult'],
    booking: { type: 'appointment', requiresAddress: false, slotDuration: 60, ctaLabel: 'احجز استشارة' },
  },
  {
    id: 'photography',
    icon: '📸',
    title: 'تصوير احترافي وفيديو',
    shortTitle: 'تصوير',
    tagline: 'لحظات لا تُنسى',
    description: 'تصوير بورتريه، مناسبات، منتجات، وأفراح — احجز جلسة تصوير.',
    uiProfile: 'appointment-based',
    defaultTheme: 'slate',
    serviceIds: ['portrait-session', 'event-photography', 'product-photography', 'wedding-engagement', 'video-shoot'],
    booking: { type: 'appointment', requiresAddress: false, slotDuration: 120, ctaLabel: 'احجز جلسة تصوير' },
  },
  {
    id: 'tutoring',
    icon: '📚',
    title: 'دروس خصوصية',
    shortTitle: 'دروس',
    tagline: 'تعليم مخصص',
    description: 'دروس رياضيات، لغات، علوم، وتحضير اختبارات — حضوري أو عن بُعد.',
    uiProfile: 'appointment-based',
    defaultTheme: 'terracotta',
    serviceIds: ['math-tutoring', 'english-tutoring', 'arabic-tutoring', 'science-tutoring', 'exam-prep', 'online-tutoring'],
    booking: { type: 'appointment', requiresAddress: false, slotDuration: 60, ctaLabel: 'احجز درساً' },
  },
  {
    id: 'hotels',
    icon: '🏨',
    title: 'ضيافة وفنادق',
    shortTitle: 'فنادق',
    tagline: 'احجز إقامتك',
    description: 'غرف فندقية، أجنحة، وشاليهات — حجز مسبق بأسعار تنافسية وخدمة ضيافة مميزة.',
    uiProfile: 'appointment-based',
    defaultTheme: 'ocean',
    serviceIds: ['standard-room', 'deluxe-room', 'suite-room', 'family-suite', 'chalet-stay', 'long-stay-hotel'],
    booking: {
      type: 'stay',
      requiresAddress: false,
      ctaLabel: 'احجز غرفة',
      collectPartySize: true,
      partySizeLabel: 'عدد الضيوف',
      collectNights: true,
      skipTimeSelection: true,
      checkInTime: '16:00',
      checkOutTime: '12:00',
    },
  },
  {
    id: 'travel',
    icon: '✈️',
    title: 'سفر وسياحة',
    shortTitle: 'سفر',
    tagline: 'باقات وبرامج',
    description: 'عمرة، سياحة داخلية وخارجية، شهر عسل، وسفر شركات — خطط رحلتك مع خبراء.',
    uiProfile: 'project-based',
    defaultTheme: 'desert',
    serviceIds: ['umrah-package', 'domestic-tour', 'international-trip', 'honeymoon-package', 'corporate-travel', 'flight-hotel-bundle'],
    booking: {
      type: 'consultation',
      requiresAddress: false,
      slotDuration: 45,
      ctaLabel: 'استشارة سفر مجانية',
    },
  },
  {
    id: 'events',
    icon: '🎉',
    title: 'مناسبات وقاعات',
    shortTitle: 'مناسبات',
    tagline: 'احتفل بتميز',
    description: 'قاعات أفراح، مؤتمرات، حفلات، وتنسيق كامل — من التخطيط إلى التنفيذ.',
    uiProfile: 'appointment-based',
    defaultTheme: 'midnight',
    serviceIds: ['wedding-hall', 'conference-hall', 'birthday-venue', 'outdoor-event', 'event-planning', 'event-catering'],
    booking: {
      type: 'appointment',
      requiresAddress: false,
      slotDuration: 120,
      ctaLabel: 'احجز قاعة',
      collectPartySize: true,
      partySizeLabel: 'عدد الحضور',
    },
  },
  {
    id: 'commerce',
    icon: '🛒',
    title: 'متجر وتجارة',
    shortTitle: 'متجر',
    tagline: 'اطلب وتوصيل',
    description: 'منتجات متنوعة — اطلب عبر واتساب مع توصيل سريع وأسعار واضحة.',
    uiProfile: 'order-based',
    defaultTheme: 'terracotta',
    serviceIds: [
      'general-product', 'electronics-item', 'grocery-box',
      'custom-gift', 'wholesale-order', 'monthly-subscription',
    ],
    order: {
      ctaLabel: 'اطلب الآن',
      requiresAddress: true,
    },
  },
  {
    id: 'bodybuilding',
    icon: '💪',
    title: 'كمال أجسام وتدريب قوة',
    shortTitle: 'كمال أجسام',
    tagline: 'ابنِ جسدك',
    description: 'تدريب شخصي وحصص ضخامة — احجز عبر صفحة الحجز فقط (منفصل عن الهوكي وكرة القدم).',
    uiProfile: 'appointment-based',
    defaultTheme: 'midnight',
    serviceIds: ['bodybuilding-pt', 'hypertrophy-class', 'competition-prep', 'posing-coaching'],
    booking: { type: 'appointment', requiresAddress: false, slotDuration: 60, ctaLabel: 'احجز حصة' },
  },
  {
    id: 'football',
    icon: '⚽',
    title: 'كرة القدم',
    shortTitle: 'كرة قدم',
    tagline: 'تدريب جماعي',
    description: 'تمارين جماعية، تكتيك، حراس مرمى، ومباريات ودية — بوابة تصويت على المواعيد والملاعب.',
    uiProfile: 'appointment-based',
    defaultTheme: 'forest',
    serviceIds: ['football-team-training', 'football-match-prep', 'football-private-coaching', 'football-goalkeeper-coaching'],
    booking: {
      type: 'appointment',
      requiresAddress: false,
      slotDuration: 90,
      ctaLabel: 'بوابة تمارين كرة القدم',
      portalUrl: 'football-coaching.html',
    },
  },
  {
    id: 'hockey',
    icon: '🏑',
    title: 'النشاط الرياضي للهوكي',
    shortTitle: 'الهوكي',
    tagline: 'تمارين وتدريب الهوكي',
    description: 'بوابة تدريب الهوكي وإدارة التمارين والتصويت على المواعيد والمواقع.',
    uiProfile: 'appointment-based',
    defaultTheme: 'midnight',
    serviceIds: ['hockey-training', 'hockey-match', 'hockey-private-coaching'],
    booking: { type: 'appointment', requiresAddress: false, slotDuration: 90, ctaLabel: 'بوابة تمارين الهوكي', portalUrl: 'coaching.html' },
  },
  {
    id: 'tailoring',
    icon: '🪡',
    title: 'تفصيل الثياب الرجالية',
    shortTitle: 'تفصيل ثياب',
    tagline: 'تفصيل راقٍ وخدمة منزلية بمتابعة كاملة',
    description: 'اختر قماشك وموديلك المفضل، وسنقوم بأخذ مقاساتك في منزلك مجاناً وتحديثك بالواتساب مع تتبع ثوبك خطوة بخطوة.',
    uiProfile: 'order-based',
    defaultTheme: 'midnight',
    serviceIds: [
      'fabric-japanese-cotton',
      'fabric-korean-practical',
      'fabric-winter-wool'
    ],
    order: {
      ctaLabel: 'ابدأ تصميم ثوبك الآن',
      requiresAddress: true,
    }
  }
];
