/**
 * كتالوج جميع الخدمات — مرتبطة بأنشطة رئيسية عبر activityId
 * الأنشطة: maintenance | tech-digital | it-support | cleaning | renovation | security | training | barber-salon | car-care | healthcare
 */
window.MkenServicesCatalog = [
  /* ─── التشغيل والصيانة ─── */
  {
    id: 'ac',
    activityId: 'maintenance',
    icon: '❄️',
    title: 'تركيب وصيانة المكيفات',
    shortTitle: 'مكيفات',
    description: 'تركيب، صيانة، تنظيف، وإصلاح جميع أنواع المكيفات — سبليت، شباك، مركزي، وكونسول.',
    features: ['تركيب مكيفات سبليت وشباك ومركزي', 'تنظيف وتعقيم المكيفات', 'تعبئة غاز الفريون', 'إصلاح الكمبروسر'],
    featured: true,
    category: 'تكييف',
    svg: '<rect x="12" y="16" width="24" height="16" rx="2" stroke="currentColor" stroke-width="2"/><path d="M12 22h24M18 16v-4M30 16v-4" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>',
  },
  {
    id: 'plumbing',
    activityId: 'maintenance',
    icon: '🚿',
    title: 'سباكة',
    shortTitle: 'سباكة',
    description: 'حلول سباكة احترافية — تسربات، انسدادات، وضعف ضغط الماء.',
    features: ['كشف وإصلاح التسربات', 'تسليك المجاري', 'تركيب وصيانة الخلاطات'],
    category: 'سباكة',
    svg: '<path d="M18 14v6a6 6 0 0012 0v-6" stroke="currentColor" stroke-width="2"/><path d="M16 32c0-4 3-6 8-6s8 2 8 6" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'electrical',
    activityId: 'maintenance',
    icon: '⚡',
    title: 'كهرباء',
    shortTitle: 'كهرباء',
    description: 'أعمال كهربائية آمنة ومعتمدة — من القواطع والإنارة إلى الأعطال الطارئة.',
    features: ['إصلاح الأعطال الكهربائية', 'تركيب الإنارة', 'صيانة اللوحات'],
    category: 'كهرباء',
    svg: '<path d="M26 12l-2 10h6l-8 14 2-10h-6l8-14z" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'general',
    activityId: 'maintenance',
    icon: '🔧',
    title: 'صيانة عامة',
    shortTitle: 'صيانة عامة',
    description: 'صيانة شاملة للمنازل والمكاتب — أبواب، نوافذ، وأثاث ثابت.',
    features: ['إصلاح الأبواب', 'صيانة الجدران', 'تركيب الأرفف'],
    category: 'صيانة',
    svg: '<path d="M16 28l4-8h8l4 8M20 20v-4a4 4 0 018 0v4" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'cleaning',
    activityId: 'cleaning',
    icon: '🧹',
    title: 'نظافة منزلية ومكتبية',
    shortTitle: 'نظافة',
    description: 'تنظيف عميق للمنازل والفلل والمكاتب — تعقيم وتنظيف ما بعد التشطيب.',
    features: ['تنظيف عميق', 'تنظيف مكاتب', 'تنظيف ما بعد التشطيب'],
    category: 'نظافة',
    svg: '<path d="M14 34l6-18 4 8 6-4-4 14H14z" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'cameras',
    activityId: 'security',
    icon: '📹',
    title: 'تركيب وصيانة الكاميرات',
    shortTitle: 'كاميرات',
    description: 'تركيب وصيانة أنظمة المراقبة CCTV — داخلية وخارجية مع ربط بالجوال.',
    features: ['تركيب كاميرات', 'صيانة أنظمة المراقبة', 'ربط بالجوال'],
    featured: true,
    category: 'أمن',
    svg: '<rect x="10" y="18" width="28" height="18" rx="3" stroke="currentColor" stroke-width="2"/><circle cx="24" cy="27" r="5" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'painting',
    activityId: 'renovation',
    icon: '🎨',
    title: 'دهانات وديكور',
    shortTitle: 'دهانات',
    description: 'دهان داخلي وخارجي — تحضير الجدران ومعالجة الرطوبة.',
    features: ['دهان داخلي وخارجي', 'معالجة الرطوبة', 'ديكورات جدارية'],
    category: 'تشطيب',
    svg: '<path d="M12 32c0-8 4-14 12-14s12 6 12 14" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'carpentry',
    activityId: 'renovation',
    icon: '🪚',
    title: 'نجارة وأبواب',
    shortTitle: 'نجارة',
    description: 'تركيب وصيانة الأبواب والخزائن والمطابخ.',
    features: ['تركيب الأبواب', 'صيانة الخزائن', 'نجارة مخصصة'],
    category: 'نجارة',
    svg: '<rect x="14" y="12" width="20" height="28" rx="2" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'pest-control',
    activityId: 'maintenance',
    icon: '🐛',
    title: 'مكافحة حشرات',
    shortTitle: 'مكافحة حشرات',
    description: 'رش وتعقيم آمن ضد الحشرات والقوارض.',
    features: ['رش مبيدات معتمدة', 'مكافحة النمل والصراصير', 'تعقيم شامل'],
    category: 'صحة',
    svg: '<circle cx="24" cy="26" r="10" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'tank-cleaning',
    activityId: 'maintenance',
    icon: '💧',
    title: 'تنظيف خزانات المياه',
    shortTitle: 'خزانات',
    description: 'تنظيف وتعقيم خزانات المياه الأرضية والعلوية.',
    features: ['تنظيف خزانات', 'تعقيم وتطهير', 'كشف التسربات'],
    category: 'سباكة',
    svg: '<ellipse cx="24" cy="30" rx="14" ry="10" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'insulation',
    activityId: 'maintenance',
    icon: '🏠',
    title: 'عزل حراري ومائي',
    shortTitle: 'عزل',
    description: 'عزل الأسقف والجدران — يقلل استهلاك الكهرباء.',
    features: ['عزل أسقف وجدران', 'عزل خزانات', 'عزل فوم'],
    category: 'عزل',
    svg: '<path d="M8 28l16-14 16 14v10H8V28z" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'appliances',
    activityId: 'maintenance',
    icon: '🔌',
    title: 'صيانة أجهزة منزلية',
    shortTitle: 'أجهزة',
    description: 'إصلاح الغسالات والثلاجات والأفران بقطع غيار أصلية.',
    features: ['صيانة غسالات وثلاجات', 'إصلاح أفران', 'صيانة سخانات'],
    category: 'أجهزة',
    svg: '<rect x="14" y="14" width="20" height="24" rx="2" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'smart-home',
    activityId: 'security',
    icon: '📱',
    title: 'أنظمة منزل ذكي',
    shortTitle: 'منزل ذكي',
    description: 'تركيب وبرمجة أنظمة التحكم الذكي — إنارة، مكيفات، وأقفال.',
    features: ['تركيب أنظمة ذكية', 'ربط الإنارة والمكيفات', 'برمجة سيناريوهات'],
    category: 'تقنية',
    svg: '<rect x="16" y="8" width="16" height="28" rx="3" stroke="currentColor" stroke-width="2"/>',
  },

  /* ─── صيانة الحاسب والشبكات ─── */
  {
    id: 'computer',
    activityId: 'it-support',
    icon: '💻',
    title: 'صيانة وتجميع الحاسب الآلي',
    shortTitle: 'حاسب آلي',
    description: 'تجميع وصيانة أجهزة الكمبيوتر — ترقية قطع، تثبيت أنظمة التشغيل، وإصلاح الأعطال البرمجية والهاردوير.',
    features: [
      'تجميع أجهزة مخصصة (Gaming & Office)',
      'صيانة كمبيوتر مكتبي',
      'ترقية رام وهاردسك SSD',
      'تثبيت ويندوز والبرامج الأساسية',
    ],
    priceLabel: 'من 150 ر.س',
    featured: true,
    category: 'حاسب',
    svg: '<rect x="10" y="14" width="28" height="18" rx="2" stroke="currentColor" stroke-width="2"/><path d="M16 38h16" stroke="currentColor" stroke-width="2" stroke-linecap="round"/><path d="M20 38v-4h8v4" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'laptop-repair',
    activityId: 'it-support',
    icon: '💻',
    title: 'صيانة اللابتوب',
    shortTitle: 'لابتوب',
    description: 'إصلاح شاشات، بطاريات، لوحات أم، ومشاكل الحرارة — لجميع ماركات اللابتوب.',
    features: ['إصلاح الشاشة واللوحة', 'استبدال البطارية', 'تنظيف ومعالجة الحرارة', 'استبدال SSD/RAM'],
    priceLabel: 'من 200 ر.س',
    category: 'حاسب',
    svg: '<rect x="12" y="16" width="24" height="16" rx="2" stroke="currentColor" stroke-width="2"/><path d="M8 36h32" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'network-setup',
    activityId: 'it-support',
    icon: '📡',
    title: 'إعداد الشبكات والواي فاي',
    shortTitle: 'شبكات',
    description: 'تركيب وبرمجة الراوتر، تقوية إشارة WiFi، وربط الأجهزة الذكية بشبكة موحدة.',
    features: ['تركيب وبرمجة الراوتر', 'Mesh WiFi للفلل', 'كابلات شبكة منظمة', 'حل مشاكل بطء الإنترنت'],
    category: 'شبكات',
    svg: '<circle cx="24" cy="24" r="6" stroke="currentColor" stroke-width="2"/><path d="M12 32c4-6 16-6 24 0M8 36c6-8 20-8 32 0" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'printer-repair',
    activityId: 'it-support',
    icon: '🖨️',
    title: 'صيانة الطابعات',
    shortTitle: 'طابعات',
    description: 'إصلاح طابعات ليزر وحبر — تنظيف رأس الطباعة، تعبئة حبر، وربط بالشبكة.',
    features: ['إصلاح أعطال الطباعة', 'تعبئة وصيانة حبر', 'ربط طابعة شبكية', 'صيانة طابعات مكتبية'],
    category: 'طابعات',
    svg: '<rect x="14" y="12" width="20" height="24" rx="2" stroke="currentColor" stroke-width="2"/><path d="M18 28h12" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'data-recovery',
    activityId: 'it-support',
    icon: '💾',
    title: 'استعادة البيانات',
    shortTitle: 'استعادة بيانات',
    description: 'استرجاع ملفات محذوفة أو تالفة من هاردسك، SSD، USB، وهواتف — بأدوات احترافية.',
    features: ['استرجاع ملفات محذوفة', 'إصلاح هاردسك تالف', 'نسخ احتياطي آمن', 'استعادة من USB/SD'],
    category: 'بيانات',
    svg: '<rect x="14" y="16" width="20" height="20" rx="2" stroke="currentColor" stroke-width="2"/><path d="M20 24h8M20 28h5" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'virus-removal',
    activityId: 'it-support',
    icon: '🛡️',
    title: 'إزالة الفيروسات والحماية',
    shortTitle: 'حماية',
    description: 'تنظيف الفيروسات والبرمجيات الخبيثة، تثبيت مضاد فيروس، وتأمين جهازك.',
    features: ['إزالة فيروسات وMalware', 'تثبيت مضاد فيروس', 'تحديث النظام والبرامج', 'تأمين كلمات المرور'],
    category: 'أمن',
    svg: '<path d="M24 8l12 6v10c0 8-6 14-12 16-6-2-12-8-12-16V14l12-6z" stroke="currentColor" stroke-width="2"/>',
  },

  /* ─── النظافة والتعقيم ─── */
  {
    id: 'office-cleaning',
    activityId: 'cleaning',
    icon: '🏢',
    title: 'نظافة مكاتب ومحلات',
    shortTitle: 'مكاتب',
    description: 'تنظيف دوري للمكاتب والمحلات التجارية — عقود شهرية أو زيارات لمرة واحدة.',
    features: ['تنظيف يومي/أسبوعي', 'تنظيف واجهات زجاج', 'تعقيم دورات مياه', 'عقود صيانة نظافة'],
    category: 'نظافة',
    svg: '<rect x="12" y="10" width="24" height="30" rx="2" stroke="currentColor" stroke-width="2"/><path d="M18 18h12M18 24h12" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'post-construction-clean',
    activityId: 'cleaning',
    icon: '🏗️',
    title: 'تنظيف ما بعد التشطيب',
    shortTitle: 'بعد التشطيب',
    description: 'إزالة غبار البناء، تنظيف الزجاج والأرضيات، وتجهيز المكان للسكن أو الافتتاح.',
    features: ['إزالة غبار ودهانات', 'تنظيف بلاط وزجاج', 'تلميع أرضيات', 'تجهيز للتسليم'],
    featured: true,
    category: 'نظافة',
    svg: '<path d="M10 34l8-20 6 10 8-14 6 24H10z" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'carpet-cleaning',
    activityId: 'cleaning',
    icon: '🛋️',
    title: 'تنظيف سجاد وموكيت',
    shortTitle: 'سجاد',
    description: 'غسيل وتعقيم السجاد والموكيت والكنب — بمعدات بخار احترافية.',
    features: ['غسيل سجاد وموكيت', 'تنظيف كنب وبخار', 'إزالة بقع صعبة', 'تجفيف سريع'],
    category: 'نظافة',
    svg: '<rect x="8" y="22" width="32" height="14" rx="3" stroke="currentColor" stroke-width="2"/><path d="M8 28h32" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'disinfection',
    activityId: 'cleaning',
    icon: '🧴',
    title: 'تعقيم وتطهير',
    shortTitle: 'تعقيم',
    description: 'رش وتعقيم شامل للمنازل والمكاتب — مواد آمنة ومعتمدة.',
    features: ['تعقيم شامل', 'رش مبيدات آمنة', 'تطهير HVAC', 'شهادة تعقيم'],
    category: 'صحة',
    svg: '<path d="M20 8v12l-6 6a4 4 0 006 6l6-6V8" stroke="currentColor" stroke-width="2"/><circle cx="28" cy="14" r="4" stroke="currentColor" stroke-width="2"/>',
  },

  /* ─── التشطيب والديكور ─── */
  {
    id: 'tiling',
    activityId: 'renovation',
    icon: '🔲',
    title: 'بلاط وسيراميك',
    shortTitle: 'بلاط',
    description: 'تركيب بلاط أرضيات وجدران — سيراميك، بورسلان، وبديل رخام.',
    features: ['تركيب بلاط أرضيات', 'بلاط جدران ومطابخ', 'بديل رخام', 'معالجة الرطوبة'],
    category: 'تشطيب',
    svg: '<rect x="10" y="10" width="12" height="12" stroke="currentColor" stroke-width="2"/><rect x="26" y="10" width="12" height="12" stroke="currentColor" stroke-width="2"/><rect x="10" y="26" width="12" height="12" stroke="currentColor" stroke-width="2"/><rect x="26" y="26" width="12" height="12" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'wallpaper',
    activityId: 'renovation',
    icon: '🖼️',
    title: 'ورق جدران وديكور',
    shortTitle: 'ورق جدران',
    description: 'تركيب ورق جدران، ديكورات 3D، وطلاءات زخرفية — لمسة عصرية لغرفك.',
    features: ['تركيب ورق جدران', 'ديكور 3D', 'طلاءات زخرفية', 'معالجة الجدران'],
    category: 'ديكور',
    svg: '<rect x="10" y="12" width="28" height="24" rx="2" stroke="currentColor" stroke-width="2"/><path d="M10 20h28" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'kitchen-cabinets',
    activityId: 'renovation',
    icon: '🍳',
    title: 'مطابخ وخزائن',
    shortTitle: 'مطابخ',
    description: 'تصميم وتركيب مطابخ مخصصة، خزائن ملابس، ووحدات تخزين — حسب المساحة والميزانية.',
    features: ['مطابخ مخصصة', 'خزائن ملابس', 'وحدات TV', 'تصميم 3D مجاني'],
    featured: true,
    category: 'نجارة',
    svg: '<rect x="8" y="18" width="32" height="20" rx="2" stroke="currentColor" stroke-width="2"/><path d="M8 26h32" stroke="currentColor" stroke-width="2"/>',
  },

  /* ─── الأمن والمراقبة ─── */
  {
    id: 'alarm-systems',
    activityId: 'security',
    icon: '🚨',
    title: 'أنظمة إنذار وحراسة',
    shortTitle: 'إنذار',
    description: 'تركيب وبرمجة أنظمة إنذار ضد السرقة — حساسات أبواب ونوافذ، sirens، وربط بالجوال.',
    features: ['حساسات أبواب ونوافذ', 'ربط تنبيهات بالجوال', 'صيانة أنظمة قديمة', 'تكامل مع كاميرات'],
    featured: true,
    category: 'أمن',
    svg: '<path d="M24 8v4M24 36v4M8 24h4M36 24h4" stroke="currentColor" stroke-width="2"/><circle cx="24" cy="24" r="10" stroke="currentColor" stroke-width="2"/><path d="M24 18v8l4 4" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'access-control',
    activityId: 'security',
    icon: '🔐',
    title: 'تحكم بالدخول',
    shortTitle: 'تحكم دخول',
    description: 'أقفال ذكية، بطاقات RFID، وبصمة — إدارة دخول الموظفين والزوار.',
    features: ['أقفال ذكية وبصمة', 'بطاقات RFID', 'سجل دخول وخروج', 'تكامل مع الكاميرات'],
    category: 'أمن',
    svg: '<rect x="16" y="10" width="16" height="22" rx="2" stroke="currentColor" stroke-width="2"/><circle cx="24" cy="24" r="3" stroke="currentColor" stroke-width="2"/><path d="M20 32h8" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'intercom',
    activityId: 'security',
    icon: '📞',
    title: 'اتصال داخلي وجرس',
    shortTitle: 'اتصال داخلي',
    description: 'تركيب أنظمة Intercom وجرس فيديو — تواصل مع الزوار قبل فتح الباب.',
    features: ['جرس فيديو IP', 'Intercom للفلل', 'ربط بالجوال', 'فتح باب عن بُعد'],
    category: 'أمن',
    svg: '<rect x="14" y="8" width="20" height="32" rx="3" stroke="currentColor" stroke-width="2"/><circle cx="24" cy="20" r="5" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'fire-alarm',
    activityId: 'security',
    icon: '🔥',
    title: 'أنظمة إنذار الحريق',
    shortTitle: 'إنذار حريق',
    description: 'كاشفات دخان وحريق — تركيب وصيانة وفق معايير السلامة.',
    features: ['كاشفات دخان', 'كاشفات حريق', 'صيانة دورية', 'تقارير سلامة'],
    category: 'سلامة',
    svg: '<path d="M24 8c-4 8-8 12-8 18a8 8 0 0016 0c0-6-4-10-8-18z" stroke="currentColor" stroke-width="2"/>',
  },

  /* ─── التدريب والتأهيل ─── */
  {
    id: 'computer-basics',
    activityId: 'training',
    icon: '💻',
    title: 'أساسيات الحاسب',
    shortTitle: 'أساسيات حاسب',
    description: 'دورة للمبتدئين — Windows، إنترنت، بريد إلكتروني، وملفات — حضورياً أو عن بُعد.',
    deliveryMode: 'hybrid', slotDuration: 90,
    features: ['Windows وإعدادات أساسية', 'تصفح آمن وإيميل', 'إدارة الملفات', 'شهادة حضور'],
    featured: true,
    category: 'تدريب',
    svg: '<rect x="10" y="14" width="28" height="18" rx="2" stroke="currentColor" stroke-width="2"/><path d="M16 38h16" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'office-apps',
    activityId: 'training',
    icon: '📊',
    title: 'برامج Microsoft Office',
    shortTitle: 'Office',
    description: 'Excel، Word، PowerPoint — مهارات عملية للموظفين والطلاب.',
    features: ['Excel متقدم', 'Word احترافي', 'PowerPoint للعروض', 'تمارين عملية'],
    category: 'تدريب',
    svg: '<rect x="8" y="12" width="14" height="18" rx="2" stroke="currentColor" stroke-width="2"/><rect x="26" y="12" width="14" height="18" rx="2" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'cyber-awareness',
    activityId: 'training',
    icon: '🛡️',
    title: 'الوعي السيبراني',
    shortTitle: 'أمن سيبراني',
    description: 'حماية نفسك وعملك — كلمات مرور، تصيّد، وخصوصية البيانات.',
    features: ['كلمات مرور قوية', 'كشف التصيّد', 'أمان WiFi', 'نسخ احتياطي'],
    category: 'تدريب',
    svg: '<path d="M24 8l12 6v10c0 8-6 14-12 16-6-2-12-8-12-16V14l12-6z" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'web-basics',
    activityId: 'training',
    icon: '🌐',
    title: 'أساسيات الويب والتسويق',
    shortTitle: 'أساسيات ويب',
    description: 'مقدمة في المواقع، SEO، ووسائل التواصل — للأفراد وأصحاب المشاريع الصغيرة.',
    features: ['فهم المواقع والاستضافة', 'SEO مبسّط', 'سوشيال ميديا', 'Google Analytics'],
    category: 'تدريب',
    svg: '<circle cx="24" cy="24" r="14" stroke="currentColor" stroke-width="2"/><path d="M10 24h28M24 10c-4 4-4 20 0 28M24 10c4 4 4 20 0 28" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'whatsapp-business-training',
    activityId: 'training',
    icon: '💬',
    title: 'تدريب WhatsApp Business',
    shortTitle: 'واتساب Business',
    description: 'استخدام WhatsApp Business وAPI — ردود آلية، كتalog، ومتابعة العملاء.',
    deliveryMode: 'hybrid', requiresAddress: true, slotDuration: 90,
    features: ['إعداد Business App', 'منتجات وردود سريعة', 'Labels وتصنيف', 'مقدمة API'],
    category: 'تدريب',
    svg: '<path d="M12 8h24a4 4 0 014 4v16a4 4 0 01-4 4H12a4 4 0 01-4-4V12a4 4 0 014-4z" stroke="currentColor" stroke-width="2"/><path d="M16 20h16M16 26h10" stroke="currentColor" stroke-width="2"/>',
  },

  /* ─── صالونات الحلاقة والتجميل ─── */
  {
    id: 'mens-haircut',
    activityId: 'barber-salon',
    icon: '💈',
    title: 'حلاقة رجالية',
    shortTitle: 'حلاقة',
    description: 'قص شعر احترافي — كلاسيكي أو عصري، مع غسيل وتصفيف.',
    features: ['قص شعر', 'غسيل وتصفيف', 'استشارة ستايل', 'موعد بدون انتظار'],
    featured: true,
    slotDuration: 30,
    category: 'حلاقة',
    svg: '<path d="M16 12l8 24M32 12l-8 24" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>',
  },
  {
    id: 'beard-grooming',
    activityId: 'barber-salon',
    icon: '🧔',
    title: 'عناية باللحية',
    shortTitle: 'لحية',
    description: 'تهذيب وتشكيل اللحية — حلاقة بالموس أو ماكينة مع زيوت طبيعية.',
    features: ['تهذيب وتشكيل', 'حلاقة بالموس', 'زيوت وترطيب', 'بخار وجه'],
    slotDuration: 20,
    category: 'حلاقة',
    svg: '<path d="M14 20c0 8 4 14 10 14s10-6 10-14" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'kids-haircut',
    activityId: 'barber-salon',
    icon: '👦',
    title: 'حلاقة أطفال',
    shortTitle: 'أطفال',
    description: 'قص شعر للأطفال في بيئة مريحة — حلاقون محترفون مع الأطفال.',
    features: ['بيئة مريحة', 'قص سريع', 'أسلوب عصري', 'مواعيد مرنة'],
    slotDuration: 25,
    category: 'حلاقة',
    svg: '<circle cx="24" cy="18" r="8" stroke="currentColor" stroke-width="2"/><path d="M12 38c0-8 5-14 12-14s12 6 12 14" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'hair-dye',
    activityId: 'barber-salon',
    icon: '🎨',
    title: 'صبغ وتلوين الشعر',
    shortTitle: 'صبغ',
    description: 'صبغ شعر ولحية — ألوان طبيعية وعصرية بمواد آمنة.',
    features: ['صبغ كامل', 'هايلايت', 'صبغ لحية', 'مواد آمنة'],
    slotDuration: 60,
    category: 'تجميل',
    svg: '<path d="M20 8v32M28 8v32M16 20h16" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'facial-mens',
    activityId: 'barber-salon',
    icon: '🧖',
    title: 'عناية بالبشرة (رجالي)',
    shortTitle: 'عناية بشرة',
    description: 'تنظيف بشرة، بخار، وقناع — للرجال.',
    features: ['تنظيف عميق', 'بخار وقناع', 'ترطيب', 'مساج وجه'],
    slotDuration: 45,
    category: 'تجميل',
    svg: '<circle cx="24" cy="24" r="14" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'womens-haircut',
    activityId: 'barber-salon',
    icon: '💇',
    title: 'قص وتصفيف (نسائي)',
    shortTitle: 'نسائي',
    description: 'قص، تصفيف، و blow-dry — لجميع أنواع الشعر.',
    features: ['قص وتصفيف', 'Blow-dry', 'تسريحات', 'استشارة مجانية'],
    slotDuration: 45,
    category: 'تجميل',
    svg: '<path d="M24 8c-6 0-10 6-10 14v6h20v-6c0-8-4-14-10-14z" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'manicure',
    activityId: 'barber-salon',
    icon: '💅',
    title: 'مانيكير وباديكير',
    shortTitle: 'أظافر',
    description: 'عناية بالأظافر — تنظيف، ترطيب، وطلاء.',
    features: ['مانيكير', 'باديكير', 'طلاء gel', 'ترطيب'],
    slotDuration: 40,
    category: 'تجميل',
    svg: '<path d="M18 32l4-16 4 8 4-12 4 20H18z" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'home-barber',
    activityId: 'barber-salon',
    icon: '🏠',
    title: 'حلاقة منزلية',
    shortTitle: 'حلاقة منزل',
    description: 'حلاق يصل إلى منزلك — للرجال والأطفال.',
    features: ['حلاقة في منزلك', 'معدات معقمة', 'مواعيد مرنة', 'للفلل والمناسبات'],
    requiresAddress: true,
    slotDuration: 45,
    category: 'حلاقة',
    svg: '<path d="M8 28l16-14 16 14v10H8V28z" stroke="currentColor" stroke-width="2"/>',
  },

  /* ─── مغاسل وعناية السيارات ─── */
  {
    id: 'quick-wash',
    activityId: 'car-care',
    icon: '💦',
    title: 'غسيل سريع (خارجي)',
    shortTitle: 'غسيل سريع',
    description: 'غسيل خارجي سريع — 15-20 دقيقة، سيارتك جاهزة.',
    features: ['غسيل خارجي', 'تجفيف', 'تنظيف زجاج', 'سريع واقتصادي'],
    featured: true,
    slotDuration: 20,
    category: 'غسيل',
    svg: '<path d="M8 28h32l-4-12H12l-4 12z" stroke="currentColor" stroke-width="2"/><circle cx="16" cy="32" r="3" stroke="currentColor" stroke-width="2"/><circle cx="32" cy="32" r="3" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'full-wash',
    activityId: 'car-care',
    icon: '🚗',
    title: 'غسيل كامل (خارجي + داخلي)',
    shortTitle: 'غسيل كامل',
    description: 'غسيل شامل خارجي وداخلي — مقاعد، لوحة، وعجلات.',
    features: ['غسيل خارجي وداخلي', 'تنظيف مقاعد', 'تلميع لوحة', 'تنظيف عجلات'],
    slotDuration: 45,
    category: 'غسيل',
    svg: '<path d="M10 28h28l-3-10H13l-3 10z" stroke="currentColor" stroke-width="2"/><rect x="14" y="14" width="20" height="8" rx="2" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'interior-detailing',
    activityId: 'car-care',
    icon: '🪑',
    title: 'تنظيف داخلي عميق',
    shortTitle: 'تنظيف داخلي',
    description: 'Detailing داخلي — بخار، تنظيف فتحات التكييف، وإزالة بقع.',
    features: ['بخار للمقاعد', 'تنظيف سقف', 'تعطير', 'تنظيف فتحات AC'],
    slotDuration: 90,
    category: 'تفصيل',
    svg: '<rect x="12" y="16" width="24" height="20" rx="3" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'polish-wax',
    activityId: 'car-care',
    icon: '✨',
    title: 'تلميع وشمع',
    shortTitle: 'تلميع',
    description: 'تلميع احترافي وشمع — حماية الطلاء ولمعان يدوم.',
    features: ['تلميع الطلاء', 'شمع حماية', 'تلميع كروم', 'حماية UV'],
    slotDuration: 120,
    category: 'تفصيل',
    svg: '<path d="M24 8l4 12h12l-10 8 4 12-10-8-10 8 4-12-10-8h12z" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'engine-clean',
    activityId: 'car-care',
    icon: '⚙️',
    title: 'تنظيف محرك',
    shortTitle: 'محرك',
    description: 'تنظيف وتلميع حجرة المحرك — بمواد آمنة على المكونات.',
    features: ['تنظيف آمن', 'إزالة grease', 'تلميع', 'فحص بصري'],
    slotDuration: 60,
    category: 'تفصيل',
    svg: '<rect x="14" y="14" width="20" height="20" rx="2" stroke="currentColor" stroke-width="2"/><path d="M18 22h12M18 26h8" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'mobile-car-wash',
    activityId: 'car-care',
    icon: '📍',
    title: 'غسيل سيارات متنقل',
    shortTitle: 'غسيل متنقل',
    description: 'نأتي إلى موقعك — منزل، مكتب، أو موقف — ونغسل سيارتك.',
    features: ['نصل إليك', 'غسيل خارجي وداخلي', 'بدون مياه (اختياري)', 'مواعيد مرنة'],
    requiresAddress: true,
    slotDuration: 60,
    category: 'غسيل',
    svg: '<circle cx="24" cy="24" r="14" stroke="currentColor" stroke-width="2"/><path d="M24 14v10l6 6" stroke="currentColor" stroke-width="2"/>',
  },

  /* ─── الخدمات الطبية والصحية ─── */
  {
    id: 'gp-consultation',
    activityId: 'healthcare',
    icon: '👨‍⚕️',
    title: 'كشف طبي عام',
    shortTitle: 'كشف طبي',
    description: 'استشارة طبيب عام — تشخيص أولي ومتابعة.',
    features: ['كشف سريري', 'وصفة طبية', 'متابعة', 'مواعيد مرنة'],
    featured: true,
    slotDuration: 30,
    category: 'طب عام',
    svg: '<circle cx="24" cy="16" r="8" stroke="currentColor" stroke-width="2"/><path d="M12 38c0-8 5-14 12-14s12 6 12 14" stroke="currentColor" stroke-width="2"/><path d="M24 24v8M20 28h8" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'home-nursing',
    activityId: 'healthcare',
    icon: '💉',
    title: 'تمريض ورعاية منزلية',
    shortTitle: 'تمريض',
    description: 'ممرض/ة معتمد في منزلك — حقن، ضماد، وقياسات حيوية.',
    features: ['حقن ومحاليل', 'ضماد جروح', 'قياسات حيوية', 'رعاية كبار السن'],
    requiresAddress: true,
    slotDuration: 60,
    category: 'تمريض',
    svg: '<path d="M24 12v24M12 24h24" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'home-lab',
    activityId: 'healthcare',
    icon: '🧪',
    title: 'تحاليل منزلية',
    shortTitle: 'تحاليل',
    description: 'سحب عينات في منزلك — تحاليل دم وبول مع نتائج سريعة.',
    features: ['سحب في المنزل', 'تحاليل شاملة', 'نتائج إلكترونية', 'مواعيد صباحية'],
    requiresAddress: true,
    slotDuration: 30,
    category: 'مختبر',
    svg: '<rect x="16" y="10" width="16" height="28" rx="2" stroke="currentColor" stroke-width="2"/><path d="M20 18h8M20 24h5" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'physiotherapy',
    activityId: 'healthcare',
    icon: '🦴',
    title: 'علاج طبيعي',
    shortTitle: 'علاج طبيعي',
    description: 'جلسات علاج طبيعي — إصابات، ظهر، وإعادة تأهيل.',
    features: ['تقييم أولي', 'تمارين علاجية', 'تدليك طبي', 'خطة متابعة'],
    slotDuration: 45,
    category: 'تأهيل',
    svg: '<path d="M14 32l6-16 4 8 6-12 4 20H14z" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'dental-checkup',
    activityId: 'healthcare',
    icon: '🦷',
    title: 'فحص أسنان',
    shortTitle: 'أسنان',
    description: 'فحص دوري للأسنان — تنظيف، أشعة، واستشارة.',
    features: ['فحص شامل', 'تنظيف أسنان', 'أشعة (إن لزم)', 'خطة علاج'],
    slotDuration: 30,
    category: 'أسنان',
    svg: '<path d="M16 20c0-4 2-8 8-8s8 4 8 8c0 6-2 12-8 12s-8-6-8-12z" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'telemedicine',
    activityId: 'healthcare',
    icon: '📱',
    title: 'استشارة طبية عن بُعد',
    shortTitle: 'عن بُعد',
    description: 'استشارة فيديو مع طبيب — من منزلك، مع وصفة إلكترونية.',
    features: ['مكالمة فيديو', 'وصفة إلكترونية', 'متابعة', '24/7 للحالات البسيطة'],
    slotDuration: 20,
    category: 'عن بُعد',
    svg: '<rect x="14" y="8" width="20" height="32" rx="3" stroke="currentColor" stroke-width="2"/><circle cx="24" cy="28" r="2" fill="currentColor"/>',
  },

  /* ─── سبا ومساج ─── */
  {
    id: 'swedish-massage', activityId: 'spa-wellness', icon: '💆', title: 'مساج سويدي', shortTitle: 'سويدي',
    description: 'مساج استرخائي للجسم كامل — يخفف التوتر ويحسّن الدورة الدموية.', slotDuration: 60,
    features: ['60 دقيقة', 'زيوت عطرية', 'استرخاء عميق'], featured: true, category: 'مساج',
    svg: '<circle cx="24" cy="20" r="8" stroke="currentColor" stroke-width="2"/><path d="M12 38c4-10 16-10 24 0" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'moroccan-bath', activityId: 'spa-wellness', icon: '🛁', title: 'حمام مغربي', shortTitle: 'مغربي',
    description: 'حمام مغربي تقليدي — بخار، تقشير، وصابون بلدي.', slotDuration: 90,
    features: ['بخار وتقشير', 'صابون بلدي', 'ترطيب'], category: 'حمام',
    svg: '<ellipse cx="24" cy="28" rx="16" ry="10" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'facial-spa', activityId: 'spa-wellness', icon: '✨', title: 'عناية بالوجه', shortTitle: 'وجه',
    description: 'تنظيف، تقشير، وقناع — بشرة مشرقة ومنتعشة.', slotDuration: 45,
    features: ['تنظيف عميق', 'قناع مغذّي', 'مساج وجه'], category: 'عناية',
    svg: '<circle cx="24" cy="24" r="14" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'body-scrub', activityId: 'spa-wellness', icon: '🧴', title: 'تقشير الجسم', shortTitle: 'تقشير',
    description: 'تقشير الجسم بملح البحر والزيوت — بشرة ناعمة.', slotDuration: 45,
    features: ['ملح البحر', 'ترطيب', 'بشرة ناعمة'], category: 'عناية',
    svg: '<path d="M20 8v32M28 8v32" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'couples-spa', activityId: 'spa-wellness', icon: '💑', title: 'سبا للأزواج', shortTitle: 'أزواج',
    description: 'جلسة سبا مزدوجة — مساج واسترخاء للاثنين.', slotDuration: 90,
    features: ['غرفة خاصة', 'مساج مزدوج', 'مشروبات'], category: 'باقات',
    svg: '<circle cx="18" cy="20" r="6" stroke="currentColor" stroke-width="2"/><circle cx="30" cy="20" r="6" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'home-spa', activityId: 'spa-wellness', icon: '🏠', title: 'سبا منزلي', shortTitle: 'منزلي',
    description: 'فني سبا يصل إلى منزلك — مساج وعناية في خصوصيتك.', slotDuration: 90, requiresAddress: true,
    features: ['نصل إليك', 'معدات كاملة', 'خصوصية'], category: 'منزلي',
    svg: '<path d="M8 28l16-14 16 14v10H8V28z" stroke="currentColor" stroke-width="2"/>',
  },

  /* ─── رياضة ولياقة ─── */
  {
    id: 'personal-training', activityId: 'fitness', icon: '🏋️', title: 'تدريب شخصي', shortTitle: 'PT',
    description: 'مدرب شخصي — برنامج مخصص لأهدافك.', slotDuration: 60, maxPerSlot: 1, featured: true,
    features: ['برنامج مخصص', 'متابعة أسبوعية', 'تغذية'], category: 'تدريب',
    svg: '<path d="M14 32l6-16h8l6 16M20 16v-4a4 4 0 018 0v4" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'yoga-session', activityId: 'fitness', icon: '🧘', title: 'جلسة اليوga', shortTitle: 'يوga',
    description: 'يوga للمبتدئين والمتقدمين — مرونة واسترخاء.', slotDuration: 60,
    features: ['Hatha / Vinyasa', 'مجموعات صغيرة', 'سجادة متوفرة'], category: 'يوga',
    svg: '<circle cx="24" cy="12" r="4" stroke="currentColor" stroke-width="2"/><path d="M12 36l12-16 12 16" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'gym-day-pass', activityId: 'fitness', icon: '🎫', title: 'دخول يومي للنادي', shortTitle: 'يومي',
    description: 'دخول يوم واحد — جميع الأجهزة والمرافق.', slotDuration: 480,
    features: ['جميع الأجهزة', 'غرفة بخار', 'مواقف'], category: 'عضوية',
    svg: '<rect x="12" y="14" width="24" height="20" rx="2" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'group-class', activityId: 'fitness', icon: '👥', title: 'حصة جماعية', shortTitle: 'جماعي',
    description: 'Zumba، CrossFit، أو Spinning — طاقة وحماس.', slotDuration: 45, maxPerSlot: 12,
    features: ['Zumba / CrossFit', 'مدرب محترف', 'مجموعة محفزة'], category: 'حصص',
    svg: '<circle cx="16" cy="24" r="4" stroke="currentColor" stroke-width="2"/><circle cx="24" cy="20" r="4" stroke="currentColor" stroke-width="2"/><circle cx="32" cy="24" r="4" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'nutrition-consult', activityId: 'fitness', icon: '🥗', title: 'استشارة تغذية', shortTitle: 'تغذية',
    description: 'أخصائي تغذية — خطة غذائية مخصصة.', slotDuration: 45,
    features: ['تحليل غذائي', 'خطة أسبوعية', 'متابعة'], category: 'تغذية',
    svg: '<path d="M14 34l6-18 4 8 6-4-4 14H14z" stroke="currentColor" stroke-width="2"/>',
  },

  /* ─── خدمات بيطرية ─── */
  {
    id: 'vet-checkup', activityId: 'veterinary', icon: '🐕', title: 'كشف بيطري', shortTitle: 'كشف',
    description: 'فحص شامل لحيوانك الأليف — كلاب، قطط، وطيور.', slotDuration: 30, featured: true,
    features: ['فحص سريري', 'نصائح رعاية', 'سجل طبي'], category: 'كشف',
    svg: '<circle cx="24" cy="22" r="10" stroke="currentColor" stroke-width="2"/><path d="M14 14l4 4M34 14l-4 4" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'pet-vaccination', activityId: 'veterinary', icon: '💉', title: 'تطعيم حيوانات', shortTitle: 'تطعيم',
    description: 'تطعيمات دورية — rabies، parvo، وغيرها.', slotDuration: 20,
    features: ['تطعيمات معتمدة', 'شهادة', 'تذكير دوري'], category: 'تطعيم',
    svg: '<path d="M24 8v24M20 32h8" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'pet-grooming', activityId: 'veterinary', icon: '✂️', title: 'تجميل حيوانات', shortTitle: 'تجميل',
    description: 'قص شعر، أظافر، وحمام — لحيوانك الأليف.', slotDuration: 60,
    features: ['قص شعر', 'قص أظافر', 'حمام'], category: 'تجميل',
    svg: '<path d="M16 28l4-8h8l4 8" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'home-vet-visit', activityId: 'veterinary', icon: '🏠', title: 'زيارة بيطرية منزلية', shortTitle: 'منزلي',
    description: 'طبيب بيطري يزور منزلك — للحيوانات التي تتوتر خارج المنزل.', slotDuration: 45, requiresAddress: true,
    features: ['نصل إليك', 'فحص في المنزل', 'أقل إجهاد للحيوان'], category: 'منزلي',
    svg: '<path d="M8 28l16-14 16 14v10H8V28z" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'pet-surgery-consult', activityId: 'veterinary', icon: '🏥', title: 'استشارة جراحية', shortTitle: 'جراحة',
    description: 'تقييم قبل العمليات — sterilization، إزالة أورام.', slotDuration: 30,
    features: ['تقييم شامل', 'خطة علاج', 'تقدير تكلفة'], category: 'جراحة',
    svg: '<rect x="14" y="12" width="20" height="24" rx="2" stroke="currentColor" stroke-width="2"/>',
  },

  /* ─── مطاعم ─── */
  {
    id: 'table-booking', activityId: 'restaurant', icon: '🍽️', title: 'حجز طاولة', shortTitle: 'طاولة',
    description: 'احجز طاولتك — بدون انتظار، حسب عدد الأشخاص.', slotDuration: 90, featured: true,
    features: ['حجز مسبق', 'بدون انتظار', 'طلبات خاصة'], category: 'حجز',
    svg: '<rect x="10" y="20" width="28" height="12" rx="2" stroke="currentColor" stroke-width="2"/><path d="M16 20v-6M32 20v-6" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'private-dining', activityId: 'restaurant', icon: '🚪', title: 'غرفة خاصة', shortTitle: 'خاص',
    description: 'غرفة VIP للعائلات والمناسبات — قائمة مخصصة.', slotDuration: 120,
    features: ['غرفة VIP', 'قائمة مخصصة', 'خدمة خاصة'], category: 'VIP',
    svg: '<rect x="12" y="10" width="24" height="28" rx="2" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'buffet-reservation', activityId: 'restaurant', icon: '🍱', title: 'حجز بوفيه', shortTitle: 'بوفيه',
    description: 'بوفيه مفتوح — فطور، غداء، أو عشاء.', slotDuration: 90,
    features: ['بوفيه مفتوح', 'أطباق متنوعة', 'حجز مجموعات'], category: 'بوفيه',
    svg: '<rect x="8" y="16" width="32" height="20" rx="2" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'catering-tasting', activityId: 'restaurant', icon: '👨‍🍳', title: 'تذوق قائمة', shortTitle: 'تذوق',
    description: 'جلسة تذوق للمناسبات — اختيار قائمة الطعام.', slotDuration: 60,
    features: ['تذوق أطباق', 'تخصيص قائمة', 'للمناسبات'], category: 'مناسبات',
    svg: '<path d="M12 32c0-8 6-14 12-14s12 6 12 14" stroke="currentColor" stroke-width="2"/>',
  },

  /* ─── استشارات مهنية ─── */
  {
    id: 'legal-consult', activityId: 'consulting', icon: '⚖️', title: 'استشارة قانونية', shortTitle: 'قانون',
    description: 'محامٍ مختص — عقود، قضايا، واستشارات.', slotDuration: 60, featured: true,
    features: ['مراجعة عقود', 'استشارة قضية', 'سرية تامة'], category: 'قانون',
    svg: '<path d="M12 36h24M16 36V16l8-8 8 8v20" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'accounting-consult', activityId: 'consulting', icon: '📊', title: 'استشارة محاسبية', shortTitle: 'محاسبة',
    description: 'محاسب قانوني — ضرائب، زكاة، وقوائم مالية.', slotDuration: 60,
    features: ['ZATCA / ضريبة', 'قوائم مالية', 'زكاة'], category: 'محاسبة',
    svg: '<rect x="10" y="14" width="28" height="22" rx="2" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'real-estate-viewing', activityId: 'consulting', icon: '🏢', title: 'معاينة عقارية', shortTitle: 'عقارات',
    description: 'معاينة شقة أو فيلا مع مستشار — شراء أو إيجار.', slotDuration: 60, requiresAddress: true,
    features: ['معاينة موجهة', 'تقييم السعر', 'نصائح شراء'], category: 'عقارات',
    svg: '<rect x="12" y="10" width="24" height="30" rx="2" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'business-consult', activityId: 'consulting', icon: '💼', title: 'استشارة أعمال', shortTitle: 'أعمال',
    description: 'مستشار أعمال — نمو، تسويق، وخطة عمل.', slotDuration: 60,
    features: ['خطة عمل', 'تحليل سوق', 'استراتيجية'], category: 'أعمال',
    svg: '<rect x="14" y="16" width="20" height="16" rx="2" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'hr-consult', activityId: 'consulting', icon: '👔', title: 'استشارة موارد بشرية', shortTitle: 'HR',
    description: 'HR — توظيف، سياسات، ونظام العمل.', slotDuration: 60,
    features: ['سياسات HR', 'توظيف', 'نظام العمل'], category: 'HR',
    svg: '<circle cx="24" cy="16" r="6" stroke="currentColor" stroke-width="2"/><path d="M10 38c0-10 6-16 14-16s14 6 14 16" stroke="currentColor" stroke-width="2"/>',
  },

  /* ─── تصوير ─── */
  {
    id: 'portrait-session', activityId: 'photography', icon: '📷', title: 'جلسة بورتريه', shortTitle: 'بورتريه',
    description: 'تصوير شخصي أو عائلي — استوديو أو outdoor.', slotDuration: 90, featured: true,
    features: ['استوديو / outdoor', 'تعديل صور', '10-20 صورة'], category: 'بورتريه',
    svg: '<rect x="10" y="16" width="28" height="20" rx="2" stroke="currentColor" stroke-width="2"/><circle cx="24" cy="26" r="6" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'event-photography', activityId: 'photography', icon: '🎉', title: 'تصوير مناسبات', shortTitle: 'مناسبات',
    description: 'حفلات، مؤتمرات، وفعاليات — تغطية كاملة.', slotDuration: 240,
    features: ['تغطية كاملة', 'ألبوم رقمي', 'فيديو (اختياري)'], category: 'مناسبات',
    svg: '<path d="M12 32l6-16 4 8 6-12 4 20H12z" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'product-photography', activityId: 'photography', icon: '📦', title: 'تصوير منتجات', shortTitle: 'منتجات',
    description: 'صور احترافية للمتاجر الإلكترونية — خلفية بيضاء أو lifestyle.', slotDuration: 120,
    features: ['خلفية بيضاء', 'retouch', 'جاهز للمتجر'], category: 'تجاري',
    svg: '<rect x="14" y="14" width="20" height="20" rx="2" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'wedding-engagement', activityId: 'photography', icon: '💍', title: 'تصوير أعراس وملكة', shortTitle: 'أعراس',
    description: 'يوم الزفاف أو جلسة ملكة — ذكريات لا تُنسى.', slotDuration: 360,
    features: ['يوم كامل', 'ألبوم فاخر', 'فيديو highlight'], category: 'أعراس',
    svg: '<circle cx="24" cy="24" r="12" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'video-shoot', activityId: 'photography', icon: '🎬', title: 'تصوير فيديو', shortTitle: 'فيديو',
    description: 'Reels، إعلانات، أو فيديو تعريفي — montage احترافي.', slotDuration: 180,
    features: ['4K', 'montage', 'موسيقى'], category: 'فيديو',
    svg: '<rect x="8" y="14" width="32" height="20" rx="2" stroke="currentColor" stroke-width="2"/><path d="M20 24l8-4v8l-8-4z" fill="currentColor"/>',
  },

  /* ─── دروس خصوصية ─── */
  {
    id: 'math-tutoring', activityId: 'tutoring', icon: '➗', title: 'رياضيات', shortTitle: 'رياضيات',
    description: 'دروس رياضيات — ابتدائي، متوسط، ثانوي، وقدرات.', slotDuration: 60, deliveryMode: 'in_person', featured: true,
    features: ['جميع المراحل', 'قدرات وتحصيلي', 'تمارين'], category: 'رياضيات',
    svg: '<path d="M16 32l8-24 8 24M18 24h12" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'english-tutoring', activityId: 'tutoring', icon: '🇬🇧', title: 'لغة إنجليزية', shortTitle: 'إنجليزي',
    description: 'English — محادثة، IELTS، وSTEP.', slotDuration: 60,
    features: ['محادثة', 'IELTS / STEP', 'قواعد'], category: 'لغات',
    svg: '<path d="M12 16h24M12 24h16M12 32h20" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'arabic-tutoring', activityId: 'tutoring', icon: '📖', title: 'لغة عربية', shortTitle: 'عربي',
    description: 'نحو، بلاغة، وتحصيلي — تقوية وتأسيس.', slotDuration: 60,
    features: ['نحو وبلاغة', 'تحصيلي', 'تأسيس'], category: 'لغات',
    svg: '<path d="M14 12h20v24H14z" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'science-tutoring', activityId: 'tutoring', icon: '🔬', title: 'علوم', shortTitle: 'علوم',
    description: 'فيزياء، كيمياء، وأحياء — ثانوي وتحصيلي.', slotDuration: 60,
    features: ['فيزياء / كيمياء', 'أحياء', 'تجارب'], category: 'علوم',
    svg: '<path d="M20 8v12l-6 6a4 4 0 006 6h8a4 4 0 006-6l-6-6V8" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'exam-prep', activityId: 'tutoring', icon: '📝', title: 'تحضير اختبارات', shortTitle: 'اختبارات',
    description: 'قدرات، تحصيلي، وIELTS — مراجعة مكثفة.', slotDuration: 90,
    features: ['نماذج اختبار', 'مراجعة', 'استراتيجيات'], category: 'اختبارات',
    svg: '<rect x="12" y="10" width="24" height="28" rx="2" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'online-tutoring', activityId: 'tutoring', icon: '💻', title: 'دروس عن بُعد', shortTitle: 'عن بُعد',
    description: 'Zoom / Teams — أي مادة، من أي مكان.', slotDuration: 60, deliveryMode: 'remote',
    features: ['Zoom', 'تسجيل الحصة', 'مرونة'], category: 'عن بُعد',
    svg: '<rect x="8" y="12" width="32" height="22" rx="2" stroke="currentColor" stroke-width="2"/>',
  },

  /* ─── ضيافة وفنادق ─── */
  {
    id: 'standard-room', activityId: 'hotels', icon: '🛏️', title: 'غرفة قياسية', shortTitle: 'قياسية',
    description: 'غرفة مزدوجة مريحة — إفطار، WiFi، وخدمة الغرف.', stayUnit: 'night', roomCount: 8, featured: true,
    features: ['سرير مزدوج', 'إفطار', 'WiFi'], category: 'غرف',
    svg: '<rect x="10" y="18" width="28" height="20" rx="2" stroke="currentColor" stroke-width="2"/><path d="M10 26h28" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'deluxe-room', activityId: 'hotels', icon: '✨', title: 'غرفة ديلوكس', shortTitle: 'ديلوكس',
    description: 'مساحة أوسع وإطلالة — مناسبة للأزواج والعائلات الصغيرة.', stayUnit: 'night', roomCount: 4,
    features: ['إطلالة', 'minibar', 'حمام فاخر'], category: 'غرف',
    svg: '<rect x="8" y="16" width="32" height="24" rx="2" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'suite-room', activityId: 'hotels', icon: '🏛️', title: 'جناح فندقي', shortTitle: 'جناح',
    description: 'جناح بغرفة معيشة — للإقامات الفاخرة والضيوف VIP.', stayUnit: 'night', roomCount: 2,
    features: ['غرفة معيشة', 'VIP', 'خدمة خاصة'], category: 'أجنحة',
    svg: '<rect x="6" y="14" width="36" height="26" rx="2" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'family-suite', activityId: 'hotels', icon: '👨‍👩‍👧‍👦', title: 'جناح عائلي', shortTitle: 'عائلي',
    description: 'جناح واسع لـ 4–6 أشخاص — مطبخ صغير وغرف نوم متعددة.', stayUnit: 'night', roomCount: 3,
    features: ['4–6 أشخاص', 'مطبخ', 'غرفتان'], category: 'أجنحة',
    svg: '<circle cx="16" cy="22" r="4" stroke="currentColor" stroke-width="2"/><circle cx="32" cy="22" r="4" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'chalet-stay', activityId: 'hotels', icon: '🏡', title: 'شاليه', shortTitle: 'شاليه',
    description: 'شاليه خاص بحديقة أو مسبح — مثالي للعطلات.', stayUnit: 'night', roomCount: 2,
    features: ['خصوصية', 'حديقة', 'مسبح'], category: 'شاليهات',
    svg: '<path d="M12 32V20l12-10 12 10v12" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'long-stay-hotel', activityId: 'hotels', icon: '📅', title: 'إقامة طويلة', shortTitle: 'طويلة',
    description: 'أسعار خاصة للإقامات الشهرية — موظفين وعائلات.', stayUnit: 'month', roomCount: 2,
    features: ['أسعار أسبوعية', 'خصم', 'مرونة'], category: 'طويلة',
    svg: '<rect x="12" y="10" width="24" height="28" rx="2" stroke="currentColor" stroke-width="2"/>',
  },

  /* ─── سفر وسياحة ─── */
  {
    id: 'umrah-package', activityId: 'travel', icon: '🕋', title: 'باقة عمرة', shortTitle: 'عمرة',
    description: 'برامج عمرة متكاملة — طيران، فندق، نقل، ومرافق.', slotDuration: 45, featured: true,
    features: ['5–14 يوم', 'فنادق قريبة', 'نقل'], category: 'عمرة',
    svg: '<path d="M24 8l4 12h-8l4-12z" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'domestic-tour', activityId: 'travel', icon: '🏜️', title: 'سياحة داخلية', shortTitle: 'داخلية',
    description: 'العلا، أبها، جدة، الرياض — جولات منظمة داخل المملكة.', slotDuration: 45,
    features: ['نقل', 'إقامة', 'مرشد'], category: 'داخلية',
    svg: '<circle cx="24" cy="24" r="14" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'international-trip', activityId: 'travel', icon: '🌍', title: 'رحلة دولية', shortTitle: 'دولية',
    description: 'أوروبا، آسيا، وتركيا — باقات شاملة أو حسب الطلب.', slotDuration: 45,
    features: ['تأشيرة', 'طيران', 'فندق'], category: 'دولية',
    svg: '<circle cx="24" cy="24" r="12" stroke="currentColor" stroke-width="2"/><path d="M12 24h24M24 12v24" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'honeymoon-package', activityId: 'travel', icon: '💑', title: 'شهر عسل', shortTitle: 'شهر عسل',
    description: 'وجهات رومانسية — المالdives، بالي، دبي، وإسطنبول.', slotDuration: 45,
    features: ['فاخر', 'خصوصية', 'تنسيق'], category: 'شهر عسل',
    svg: '<path d="M18 28c0-4 6-8 6-12 0 4 6 8 6 12" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'corporate-travel', activityId: 'travel', icon: '💼', title: 'سفر شركات', shortTitle: 'شركات',
    description: 'إدارة سفر الموظفين — حجوزات جماعية وتقارير.', slotDuration: 45,
    features: ['فواتير', 'سياسات', 'دعم 24/7'], category: 'شركات',
    svg: '<rect x="14" y="12" width="20" height="24" rx="2" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'flight-hotel-bundle', activityId: 'travel', icon: '🎫', title: 'طيران + فندق', shortTitle: 'باقة',
    description: 'باقة موحّدة بسعر مخفّض — طيران وإقامة في حجز واحد.', slotDuration: 45,
    features: ['سعر موحّد', 'مرونة', 'توفير'], category: 'باقات',
    svg: '<path d="M8 28l8-16 8 8 8-8v16H8z" stroke="currentColor" stroke-width="2"/>',
  },

  /* ─── مناسبات وقاعات ─── */
  {
    id: 'wedding-hall', activityId: 'events', icon: '💒', title: 'قاعة أفراح', shortTitle: 'أفراح',
    description: 'قاعة فاخرة للأعراس — ديكور، صوت، وإضاءة.', slotDuration: 360, featured: true,
    features: ['500+ ضيف', 'ديكور', 'صوت'], category: 'أفراح',
    svg: '<path d="M12 32h24M16 32V20l8-8 8 8v12" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'conference-hall', activityId: 'events', icon: '🎤', title: 'قاعة مؤتمرات', shortTitle: 'مؤتمرات',
    description: 'قاعة مجهزة للمؤتمرات والندوات — شاشات وترجمة.', slotDuration: 240,
    features: ['200 مقعد', 'شاشات', 'WiFi'], category: 'مؤتمرات',
    svg: '<rect x="8" y="14" width="32" height="22" rx="2" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'birthday-venue', activityId: 'events', icon: '🎂', title: 'حفلة عيد ميلاد', shortTitle: 'عيد ميلاد',
    description: 'قاعة أو استراحة للاحتفالات العائلية — ديكور وألعاب.', slotDuration: 180,
    features: ['50–150 ضيف', 'ديكور', 'كيك'], category: 'احتفالات',
    svg: '<circle cx="24" cy="26" r="10" stroke="currentColor" stroke-width="2"/><path d="M24 16v-6M20 12h8" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'outdoor-event', activityId: 'events', icon: '🌳', title: 'مناسبة خارجية', shortTitle: 'خارجية',
    description: 'حدائق، شاطئ، أو استراحة — للفعاليات المفتوحة.', slotDuration: 300,
    features: ['خيام', 'إضاءة', 'مولدات'], category: 'خارجية',
    svg: '<circle cx="16" cy="28" r="6" stroke="currentColor" stroke-width="2"/><path d="M24 10v18" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'event-planning', activityId: 'events', icon: '📋', title: 'تنسيق مناسبات', shortTitle: 'تنسيق',
    description: 'إدارة كاملة للحدث — من الدعوات إلى التنفيذ.', slotDuration: 120,
    features: ['تخطيط', 'موردين', 'يوم الحدث'], category: 'تنسيق',
    svg: '<rect x="14" y="10" width="20" height="28" rx="2" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'event-catering', activityId: 'events', icon: '🍽️', title: 'ضيافة وبوفيه', shortTitle: 'ضيافة',
    description: 'بوفيه مفتوح، كофe break، أو قائمة مخصصة للمناسبة.', slotDuration: 180,
    features: ['بوفيه', 'خدمة', 'قائمة مخصصة'], category: 'ضيافة',
    svg: '<ellipse cx="24" cy="28" rx="14" ry="6" stroke="currentColor" stroke-width="2"/>',
  },

  /* ─── متجر وتجارة ─── */
  {
    id: 'general-product', activityId: 'commerce', icon: '🛍️', title: 'منتجات عامة', shortTitle: 'منتجات',
    description: 'منتجات متنوعة للمنزل والمكتب — اطلب ما تحتاجه.', priceLabel: 'من 49 ر.س', featured: true,
    features: ['تنوّع', 'توصيل', 'استبدال'], category: 'عام',
    svg: '<path d="M14 18h20l-2 16H16l-2-16zM18 18V14a6 6 0 0112 0v4" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'electronics-item', activityId: 'commerce', icon: '📱', title: 'إلكترونيات', shortTitle: 'إلكترونيات',
    description: 'إكسسوارات، سماعات، وملحقات — أصلية ومضمونة.', priceLabel: 'من 99 ر.س',
    features: ['ضمان', 'أصلي', 'توصيل'], category: 'إلكترونيات',
    svg: '<rect x="16" y="8" width="16" height="28" rx="3" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'grocery-box', activityId: 'commerce', icon: '🧺', title: 'بقالة وتوصيل', shortTitle: 'بقالة',
    description: 'سلة بقالة أسبوعية — خضار، ألبان، ومستلزمات.', priceLabel: 'من 120 ر.س',
    features: ['طازج', 'توصيل سريع', 'تخصيص'], category: 'بقالة',
    svg: '<path d="M12 20h24l-4 14H16L12 20z" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'custom-gift', activityId: 'commerce', icon: '🎁', title: 'هدايا مخصصة', shortTitle: 'هدايا',
    description: 'تغليف ورسالة — هدايا للمناسبات والأعياد.', priceLabel: 'من 79 ر.س',
    features: ['تغليف', 'بطاقة', 'توصيل'], category: 'هدايا',
    svg: '<rect x="14" y="18" width="20" height="16" rx="2" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'wholesale-order', activityId: 'commerce', icon: '📦', title: 'طلب جملة', shortTitle: 'جملة',
    description: 'أسعار خاصة للكميات — شركات ومشاريع.', priceLabel: 'حسب الكمية',
    features: ['خصم', 'فواتير', 'توريد'], category: 'جملة',
    svg: '<rect x="10" y="14" width="28" height="24" rx="2" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'monthly-subscription', activityId: 'commerce', icon: '🔁', title: 'اشتراك شهري', shortTitle: 'اشتراك',
    description: 'صندوق شهري أو توريد دوري — وفّر وقتك.', priceLabel: 'من 199 ر.س/شهر',
    features: ['شهري', 'مرونة', 'إلغاء سهل'], category: 'اشتراك',
    svg: '<path d="M32 16a8 8 0 11-8-8" stroke="currentColor" stroke-width="2"/><path d="M24 8v8h8" stroke="currentColor" stroke-width="2"/>',
  },

  /* ─── الحاسب والتقنية الرقمية ─── */
  {
    id: 'web-design',
    activityId: 'tech-digital',
    icon: '🌐',
    title: 'تصميم المواقع الإلكترونية',
    shortTitle: 'تصميم مواقع',
    description: 'مواقع احترافية متجاوبة — تصميم عصري، سرعة تحميل، وتجربة مستخدم ممتازة.',
    features: ['تصميم UI/UX احترافي', 'مواقع متجاوبة (Responsive)', 'CMS سهل الإدارة', 'استضافة وSSL'],
    priceLabel: 'من 2,500 ر.س',
    featured: true,
    category: 'تطوير',
    svg: '<rect x="8" y="12" width="32" height="22" rx="2" stroke="currentColor" stroke-width="2"/><path d="M8 18h32" stroke="currentColor" stroke-width="2"/><circle cx="13" cy="15" r="1.5" fill="currentColor"/>',
  },
  {
    id: 'mobile-apps',
    activityId: 'tech-digital',
    icon: '📱',
    title: 'تطبيقات الجوال',
    shortTitle: 'تطبيقات',
    description: 'تطبيقات iOS و Android — من الفكرة إلى الإطلاق في المتاجر.',
    features: ['تطبيقات iOS و Android', 'React Native / Flutter', 'ربط API وقواعد بيانات', 'نشر في App Store و Google Play'],
    priceLabel: 'من 15,000 ر.س',
    category: 'تطوير',
    svg: '<rect x="16" y="8" width="16" height="28" rx="3" stroke="currentColor" stroke-width="2"/><circle cx="24" cy="30" r="2" fill="currentColor"/>',
  },
  {
    id: 'landing-pages',
    activityId: 'tech-digital',
    icon: '🎯',
    title: 'صفحات تعريفية (Landing Pages)',
    shortTitle: 'صفحات تعريفية',
    description: 'صفحات هبوط عالية التحويل — لحملاتك الإعلانية وعروضك الترويجية.',
    features: ['تصميم يركز على التحويل', 'A/B Testing', 'تكامل مع Google Ads', 'تحليلات وPixel'],
    priceLabel: 'من 1,200 ر.س',
    category: 'تسويق',
    svg: '<path d="M12 36V16l12-8 12 8v20H12z" stroke="currentColor" stroke-width="2"/><path d="M24 8v28" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'seo',
    activityId: 'tech-digital',
    icon: '🔍',
    title: 'SEO وتحسين محركات البحث',
    shortTitle: 'SEO',
    description: 'ظهور أقوى في Google — كلمات مفتاحية، محتوى، وتحسين تقني.',
    features: ['تحليل كلمات مفتاحية', 'تحسين On-Page و Off-Page', 'Google Search Console', 'تقارير شهرية'],
    priceLabel: 'من 800 ر.س/شهر',
    category: 'تسويق',
    svg: '<circle cx="20" cy="20" r="10" stroke="currentColor" stroke-width="2"/><path d="M28 28l8 8" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>',
  },
  {
    id: 'whatsapp-crm',
    activityId: 'tech-digital',
    icon: '💬',
    title: 'واتساب CRM',
    shortTitle: 'واتساب CRM',
    description: 'نظام إدارة علاقات العملاء عبر واتساب — ردود آلية، تصنيف العملاء، ومتابعة المبيعات.',
    features: [
      'ربط WhatsApp Business API',
      'ردود آلية و Chatbot ذكي',
      'تصنيف العملاء ومراحل المبيعات',
      'إرسال جماعي وقوالب رسائل',
      'تقارير أداء الفريق',
      'تكامل مع موقعك ونظام الحجز',
    ],
    priceLabel: 'من 500 ر.س/شهر',
    featured: true,
    category: 'CRM',
    svg: '<path d="M12 8h24a4 4 0 014 4v16a4 4 0 01-4 4H12a4 4 0 01-4-4V12a4 4 0 014-4z" stroke="currentColor" stroke-width="2"/><path d="M16 20h16M16 26h10" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>',
  },
  {
    id: 'social-media',
    activityId: 'tech-digital',
    icon: '📣',
    title: 'إدارة وسائل التواصل',
    shortTitle: 'سوشيال ميديا',
    description: 'إدارة حساباتك — محتوى، تصميم، وجدولة منشورات.',
    features: ['استراتيجية محتوى', 'تصميم منشورات', 'جدولة ونشر', 'تقارير تفاعل'],
    priceLabel: 'من 600 ر.س/شهر',
    category: 'تسويق',
    svg: '<circle cx="24" cy="24" r="14" stroke="currentColor" stroke-width="2"/><path d="M18 24h12M24 18v12" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'branding',
    activityId: 'tech-digital',
    icon: '✨',
    title: 'الهوية البصرية',
    shortTitle: 'هوية بصرية',
    description: 'شعار، ألوان، وخطوط — هوية متكاملة تميّز علامتك.',
    features: ['تصميم شعار', 'دليل هوية (Brand Guide)', 'بطاقات أعمال', 'قوالب سوشيال'],
    priceLabel: 'من 1,500 ر.س',
    category: 'تصميم',
    svg: '<path d="M24 8l4 12h12l-10 8 4 12-10-8-10 8 4-12-10-8h12z" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'ecommerce',
    activityId: 'tech-digital',
    icon: '🛒',
    title: 'متاجر إلكترونية',
    shortTitle: 'متاجر',
    description: 'متجر كامل — منتجات، دفع إلكتروني، وشحن.',
    features: ['WooCommerce / Shopify', 'بوابات دفع (مدى، Apple Pay)', 'إدارة مخزون', 'تكامل شحن'],
    priceLabel: 'من 4,500 ر.س',
    category: 'تطوير',
    svg: '<path d="M10 14h4l2 16h16l2-16h4" stroke="currentColor" stroke-width="2"/><circle cx="20" cy="36" r="3" stroke="currentColor" stroke-width="2"/><circle cx="32" cy="36" r="3" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'hockey-training',
    activityId: 'hockey',
    icon: '🏑',
    title: 'حصة تدريب جماعية',
    shortTitle: 'تدريب جماعي',
    description: 'حصص تدريب جماعية مع الكوتش لتطوير مهارات اللعب الجماعي واللياقة.',
    features: ['تدريب على التكتيك والمهارات', 'تجهيز اللياقة البدنية للهوكي', 'تحت إشراف كوتش معتمد'],
    category: 'هوكي',
    svg: '<circle cx="24" cy="24" r="10" stroke="currentColor" stroke-width="2"/><path d="M24 14v20M14 24h20" stroke="currentColor" stroke-width="2"/>'
  },
  {
    id: 'hockey-match',
    activityId: 'hockey',
    icon: '🏆',
    title: 'مباراة ودية / تقسيم',
    shortTitle: 'مباراة ودية',
    description: 'مباريات ودية وتقسيمات لتطبيق المهارات التكتيكية في الملعب.',
    features: ['تنظيم المباريات والفرق', 'تحكيم وإشراف فني', 'جوائز تشجيعية'],
    category: 'هوكي',
    svg: '<path d="M12 12h24v12H12zm0 12c0 6 5 10 12 10s12-4 12-10" stroke="currentColor" stroke-width="2"/>'
  },
  {
    id: 'hockey-private-coaching',
    activityId: 'hockey',
    icon: '👤',
    title: 'تدريب شخصي خاص (PT)',
    shortTitle: 'تدريب خاص',
    description: 'حصة تدريب خاصة 1-on-1 لتطوير المهارات الفردية بدقة مع الكوتش.',
    features: ['خطة تدريب فردية مخصصة', 'تركيز على المهارات الفردية', 'مرونة عالية في تحديد المواعيد'],
    category: 'هوكي',
    svg: '<path d="M24 20a5 5 0 100-10 5 5 0 000 10zm-10 14c0-5 4-8 10-8s10 3 10 8" stroke="currentColor" stroke-width="2"/>'
  },

  /* ─── كمال أجسام ─── */
  {
    id: 'bodybuilding-pt', activityId: 'bodybuilding', icon: '💪', title: 'تدريب شخصي — كمال أجسام', shortTitle: 'PT',
    description: 'مدرب شخصي متخصص — برنامج قوة وضخامة مخصص 100%.', slotDuration: 60, maxPerSlot: 1, featured: true,
    features: ['برنامج مخصص', 'متابعة أسبوعية', 'تغذية'], category: 'شخصي',
    svg: '<path d="M14 32l6-16h8l6 16M20 16v-4a4 4 0 018 0v4" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'hypertrophy-class', activityId: 'bodybuilding', icon: '🏋️', title: 'حصة ضخامة جماعية', shortTitle: 'ضخامة',
    description: 'حصة Hypertrophy جماعية — حجم عضلي وتقنية صحيحة.', slotDuration: 60, maxPerSlot: 10,
    features: ['8–12 تكرار', 'مجموعة محفزة', 'مدرب متخصص'], category: 'جماعي',
    svg: '<rect x="10" y="18" width="28" height="16" rx="2" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'competition-prep', activityId: 'bodybuilding', icon: '🏆', title: 'إعداد مسابقات', shortTitle: 'مسابقات',
    description: 'برنامج تنشيف وإعداد لمسابقات كمال الأجسام.', slotDuration: 90, maxPerSlot: 1,
    features: ['تنشيف', 'بروتوكول مسابقة', 'متابعة يومية'], category: 'مسابقات',
    svg: '<path d="M12 28l12-16 12 16H12z" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'posing-coaching', activityId: 'bodybuilding', icon: '📐', title: 'تدريب وضعيات العرض', shortTitle: 'وضعيات',
    description: 'جلسة تدريب على وضعيات العرض أمام لجنة التحكيم.', slotDuration: 45, maxPerSlot: 1,
    features: ['Mandatory poses', 'تصحيح وضعية', 'تمارين مرآة'], category: 'مسابقات',
    svg: '<path d="M24 12v24M16 20h16" stroke="currentColor" stroke-width="2"/>',
  },

  /* ─── كرة القدم ─── */
  {
    id: 'football-team-training', activityId: 'football', icon: '⚽', title: 'تمرين جماعي', shortTitle: 'جماعي',
    description: 'تمرين كرة قدم جماعي — تكتيك ولياقة تحت إشراف المدرب.', slotDuration: 90, maxPerSlot: 22, featured: true,
    features: ['تكتيك', 'لياقة', 'تصويت على الموعد'], category: 'جماعي',
    svg: '<circle cx="24" cy="24" r="12" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'football-match-prep', activityId: 'football', icon: '🏆', title: 'إعداد مباراة ودية', shortTitle: 'مباراة',
    description: 'تحضير وتنظيم مباراة ودية أو تقسيم فرق.', slotDuration: 120, maxPerSlot: 22,
    features: ['تقسيم فرق', 'تحكيم', 'إحماء'], category: 'مباريات',
    svg: '<path d="M12 12h24v12H12zm0 12c0 6 5 10 12 10s12-4 12-10" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'football-private-coaching', activityId: 'football', icon: '👤', title: 'تدريب خاص', shortTitle: 'خاص',
    description: 'حصة 1-on-1 لتطوير المهارات الفردية.', slotDuration: 60, maxPerSlot: 1,
    features: ['مهارات فردية', 'مرونة الموعد', 'خطة مخصصة'], category: 'خاص',
    svg: '<circle cx="24" cy="18" r="6" stroke="currentColor" stroke-width="2"/><path d="M12 36c0-6 5-10 12-10s12 4 12 10" stroke="currentColor" stroke-width="2"/>',
  },
  {
    id: 'football-goalkeeper-coaching', activityId: 'football', icon: '🧤', title: 'تدريب حراس المرمى', shortTitle: 'حراس',
    description: 'تدريب متخصص لحراس المرمى — انقضاض وتمرير وتوزيع.', slotDuration: 60, maxPerSlot: 4,
    features: ['انقضاض', 'تمرير', 'توزيع الكرة'], category: 'حراس',
    svg: '<path d="M8 20h32v16H8z M16 20V12h16v8" stroke="currentColor" stroke-width="2"/>',
  },
  /* ─── تفصيل الثياب الرجالية ─── */
  {
    id: 'fabric-japanese-cotton',
    activityId: 'tailoring',
    icon: '🧵',
    title: 'تفصيل ثوب قطن ياباني فاخر',
    shortTitle: 'ياباني فاخر',
    description: 'تفصيل ثوب من أجود أنواع القطن الياباني المقاوم للتجعد والحرارة.',
    priceLabel: '280 ريال',
    featured: true,
    category: 'أقمشة صيفية',
    svg: '<rect x="12" y="12" width="24" height="24" rx="2" stroke="currentColor" stroke-width="2"/><path d="M12 18h24M12 24h24M12 30h24" stroke="currentColor" stroke-width="2"/>',
    is_fabric_roll: true,
    roll_length_total: 22.5,
    consumption_rate_per_thobe: 3.5,
  },
  {
    id: 'fabric-korean-practical',
    activityId: 'tailoring',
    icon: '🧵',
    title: 'تفصيل ثوب سلك كوري عملي',
    shortTitle: 'كوري عملي',
    description: 'تفصيل ثوب من السلك الكوري الممتاز المناسب للاستخدام اليومي والعملي.',
    priceLabel: '190 ريال',
    category: 'أقمشة صيفية',
    svg: '<rect x="12" y="12" width="24" height="24" rx="2" stroke="currentColor" stroke-width="2"/><path d="M12 18h24M12 24h24M12 30h24" stroke="currentColor" stroke-width="2"/>',
    is_fabric_roll: true,
    roll_length_total: 30.0,
    consumption_rate_per_thobe: 3.5,
  },
  {
    id: 'fabric-winter-wool',
    activityId: 'tailoring',
    icon: '🧣',
    title: 'تفصيل ثوب صوف شتوي فاخر',
    shortTitle: 'صوف شتوي',
    description: 'تفصيل ثوب من الصوف الشتوي الثقيل والفاخر بمختلف الألوان الكلاسيكية.',
    priceLabel: '390 ريال',
    category: 'أقمشة شتوية',
    svg: '<rect x="12" y="12" width="24" height="24" rx="2" stroke="currentColor" stroke-width="2"/><path d="M12 18h24M12 24h24M12 30h24" stroke="currentColor" stroke-width="2"/>',
    is_fabric_roll: true,
    roll_length_total: 20.0,
    consumption_rate_per_thobe: 3.2,
  },
  /* ─── تفصيل البدل العسكرية ─── */
  {
    id: 'uniform-land-forces',
    activityId: 'military-tailoring',
    icon: '🎖️',
    title: 'تفصيل بدلة القوات البرية (مموه)',
    shortTitle: 'بدلة برية',
    description: 'تفصيل وتجهيز بدلة القوات البرية الملكية السعودية المموهة بالمقاس والرتب والشارات الرسمية.',
    priceLabel: '450 ريال',
    category: 'بدل القوات المسلحة',
    svg: '<rect x="12" y="12" width="24" height="24" rx="2" stroke="currentColor" stroke-width="2"/><path d="M12 18h24M12 24h24M12 30h24" stroke="currentColor" stroke-width="2"/>',
    is_fabric_roll: true,
    roll_length_total: 30.0,
    consumption_rate_per_thobe: 4.0,
  },
  {
    id: 'uniform-air-forces',
    activityId: 'military-tailoring',
    icon: '🎖️',
    title: 'تفصيل بدلة القوات الجوية (مكتبية)',
    shortTitle: 'بدلة جوية',
    description: 'تفصيل وتجهيز بدلة القوات الجوية الملكية السعودية المكتبية باللون الأزرق المعتمد.',
    priceLabel: '480 ريال',
    category: 'بدل القوات المسلحة',
    svg: '<rect x="12" y="12" width="24" height="24" rx="2" stroke="currentColor" stroke-width="2"/><path d="M12 18h24M12 24h24M12 30h24" stroke="currentColor" stroke-width="2"/>',
    is_fabric_roll: true,
    roll_length_total: 30.0,
    consumption_rate_per_thobe: 4.0,
  },
  {
    id: 'uniform-navy-forces',
    activityId: 'military-tailoring',
    icon: '🎖️',
    title: 'تفصيل بدلة القوات البحرية',
    shortTitle: 'بدلة بحرية',
    description: 'تفصيل وتجهيز بدلة القوات البحرية الملكية السعودية باللون الأبيض أو الكحلي الرسمي.',
    priceLabel: '480 ريال',
    category: 'بدل القوات المسلحة',
    svg: '<rect x="12" y="12" width="24" height="24" rx="2" stroke="currentColor" stroke-width="2"/><path d="M12 18h24M12 24h24M12 30h24" stroke="currentColor" stroke-width="2"/>',
    is_fabric_roll: true,
    roll_length_total: 30.0,
    consumption_rate_per_thobe: 4.0,
  },
  {
    id: 'uniform-security-forces',
    activityId: 'military-tailoring',
    icon: '👮',
    title: 'تفصيل بدلة الأمن العام (الشرطة)',
    shortTitle: 'بدلة الأمن العام',
    description: 'تفصيل وتجهيز بدلة الأمن العام (الشرطة، المرور، الدوريات الأمنية) باللونين الأسود والرصاصي المعتمد.',
    priceLabel: '380 ريال',
    category: 'بدل الأمن العام',
    svg: '<rect x="12" y="12" width="24" height="24" rx="2" stroke="currentColor" stroke-width="2"/><path d="M12 18h24M12 24h24M12 30h24" stroke="currentColor" stroke-width="2"/>',
    is_fabric_roll: true,
    roll_length_total: 40.0,
    consumption_rate_per_thobe: 3.8,
  }
];
